---
abstract: 'Send IRC notices from your dancer app'
author:
  - 'Alan Berndt <alan@eatabrick.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.023
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.3, Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-IRCNotice
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Dancer: 0
  IO::Socket::IP: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/bentglasstube/Dancer-Plugin-IRCNotice/issues
  homepage: https://github.com/bentglasstube/Dancer-Plugin-IRCNotice
  repository: https://github.com/bentglasstube/Dancer-Plugin-IRCNotice.git
version: 0.04
